config/routes.rb
Rails.application.routes.draw do
  root 'blogs#index'
  resources :blogs do
    collection do
      post :confirm
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  with_options presence: true, length: {in:1..140} do
    validates :title
    validates :content
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  def index
    @blogs = Blog.all
  end

  def new
    @blog = Blog.new
  end

  def create
    @blog = Blog.new(blog_params)
    if params[:back]
      render :new
    else
      if @blog.save
        redirect_to blogs_path, notice: "記事「#{@blog.title}」を投稿しました！"
      else
        render :new
      end
    end
  end

  def show; end

  def edit; end

  def update
    if set_blog.update(blog_params)
      redirect_to blogs_path, notice: "記事「#{@blog.title}」を編集しました！"
    else
      render :edit
    end
  end

  def destroy
    @blog.destroy
    redirect_to blogs_path, notice: "記事「#{@blog.title}」を削除しました！"
  end

  def confirm
    @blog = Blog.new(blog_params)
    render :new if @blog.invalid?
  end

  private

  def blog_params
    params.require(:blog).permit(:title, :content)
  end

  def set_blog
    @blog = Blog.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper

  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create'
      confirm_blogs_path
    elsif action_name == 'edit'
      blog_path
    end
  end
  
end

app/views/blogs/_form.html.erb
<%= form_with(model: @blog, local: true, url: choose_new_or_edit) do |form| %>
  <% if @blog.errors.any? %>
    <div if="error_explanation">
      <h2><%= @blog.errors.count %>件のエラーがあります。</h2>
      <ul>
        <% @blog.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="blog_title">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="blog_content">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>
  <div class="blog_submit">
    <%= form.submit '投稿する'%>
  </div>
<% end %>

<%= link_to 'ブログ一覧画面へ！', blogs_path %>

app/views/blogs/confirm.html.erb
<h3>以下の内容で、送信する。</h3>
<%= form_with(model: @blog, local: true, url: choose_new_or_edit) do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
  <p>タイトル:<%= @blog.title %></p>
  <p>本文:<%= @blog.content %></p>
  <%= form.submit "登録する" %>
  <%= form.submit "戻る", name: 'back' %>
<% end %>

app/views/blogs/edit.html.erb
<h2>ブログを編集する</h2>
<%= render 'form' %>

app/views/blogs/index.html.erb
<h2>ブログ一覧</h2>
<%= notice %>
<table>
  <th>タイトル</th>
  <th>内容</th>
<% @blogs.each do |blog| %>
  <tr>
    <td><%= blog.title %></td>
    <td><%= blog.content %></td>
    <td><%= link_to '詳細を確認する', blog_path(blog.id) %></td>
    <td><%= link_to 'ブログを編集する', edit_blog_path(blog.id) %></td>
    <td><%= link_to 'ブログを削除する', blog_path(blog.id), data: {confirm: '本当に削除してもよろしいですか？'}, method: :delete %></td>
  </tr>
<% end %>
</table>

<br><%= link_to 'ブログ作成画面へ！', new_blog_path %></br>

app/views/blogs/new.html.erb
<h2>ブログを作成する</h2>
<%= render 'form' %>

app/views/blogs/show.html.erb
<h1>ブログ詳細画面</h1>
<p>タイトル:<%= @blog.title %></p>
<p>内容:<%= @blog.content %></p>

<br><%= link_to 'ブログ一覧画面へ！', blogs_path %></br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kadai2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>